name: 'Delete old artifacts'
on:
  schedule:
    - cron: '0 */12 * * *' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Weekly Artifact Cleanup
        uses: jimschubert/delete-artifacts-action@v1
        with:
          token: ${{ secrets.Token }}
          log_level: 'error'
          min_bytes: '0'
