name: 'Delete old artifacts'
on:
  schedule:
    - cron: '0 */12 * * *' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.Token }}
          expire-in: 1days # Setting this to 0 will delete all artifacts
